import { PhysicsExperimentSample } from '../types/physics';

const BASE_EXPERIMENT_VIDEOS: PhysicsExperimentSample[] = [
  // =========================================================================
  // OFFICIAL FIZZIQ CINEMATIQUE & LAB EXPERIMENTS (34 REAL EXPERIMENTS)
  // =========================================================================
  {
    id: 'fizziq-parabola',
    title: 'FizziQ: Parabolic Motion (Classic Lab)',
    source: 'FizziQ',
    category: '2D Kinematics & Projectiles',
    description: 'Real FizziQ laboratory experiment video showing a high-contrast projectile launched across a calibrated 1.00m reference ruler.',
    videoUrl: '/videos/fizziq_parabole.mp4',
    posterUrl: '/images/cinematique-posters/parabole.jpg',
    fps: 30,
    defaultMass: 0.15,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 140, y: 963 },
      rulerP2: { x: 140, y: 478 },
      origin: { x: 140, y: 963 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-freefall',
    title: 'FizziQ: Vertical Free Fall (Measure g)',
    source: 'FizziQ',
    category: '1D Kinematics & Gravity',
    description: 'Real FizziQ vertical drop acceleration measurement video. Determine experimental gravitational acceleration g ≈ 9.81 m/s².',
    videoUrl: '/videos/fizziq_chute_libre.m4v',
    posterUrl: '/images/cinematique-posters/chute-libre-balle.jpg',
    fps: 30,
    defaultMass: 0.20,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 147, y: 1634 },
      rulerP2: { x: 147, y: 930 },
      origin: { x: 651, y: 165 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-pendulum',
    title: 'FizziQ: Harmonic Pendulum Oscillation',
    source: 'FizziQ',
    category: 'Harmonic Motion & Oscillations',
    description: 'Real FizziQ high-contrast pendulum oscillation. Ideal for measuring period T, angular frequency ω, and sinusoidal curve fitting.',
    videoUrl: '/videos/fizziq_pendule.mp4',
    posterUrl: '/images/cinematique-posters/pendule.jpg',
    fps: 30,
    defaultMass: 0.20,
    rulerRealLength: 0.40,
    autoCalibrate: {
      rulerP1: { x: 165, y: 591 },
      rulerP2: { x: 411, y: 591 },
      origin: { x: 635, y: 378 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-uniform-ball',
    title: 'FizziQ: Uniform Motion (Rolling Ball)',
    source: 'FizziQ',
    category: '1D Kinematics & Constant Velocity',
    description: 'Rolling ball filmed on a level track demonstrating uniform linear motion with zero net acceleration and constant horizontal velocity vx.',
    videoUrl: '/videos/fizziq/mouvement-uniforme-balle.mp4',
    posterUrl: '/images/cinematique-posters/mouvement-uniforme-balle.jpg',
    fps: 30,
    defaultMass: 0.10,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 254, y: 278 },
      rulerP2: { x: 928, y: 278 },
      origin: { x: 1040, y: 455 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-train-uniform',
    title: 'FizziQ: Model Train Uniform Motion',
    source: 'FizziQ',
    category: '1D Kinematics & Constant Velocity',
    description: 'Electric toy locomotive traveling at constant cruising speed on straight rails. Confirms linear position x(t) = v*t with R² = 1.00.',
    videoUrl: '/videos/fizziq/train-uniforme.mp4',
    posterUrl: '/images/cinematique-posters/train-uniforme.jpg',
    fps: 25,
    defaultMass: 0.35,
    rulerRealLength: 0.50,
    autoCalibrate: {
      rulerP1: { x: 140, y: 570 },
      rulerP2: { x: 870, y: 570 },
      origin: { x: 140, y: 529 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-train-friction',
    title: 'FizziQ: Train Deceleration with Friction',
    source: 'FizziQ',
    category: 'Dynamics & Friction',
    description: 'Unpowered train car coasting to a stop under rolling resistance and rail friction. Quantify negative deceleration a and friction coefficient μ.',
    videoUrl: '/videos/fizziq/train-frottement.mp4',
    posterUrl: '/images/cinematique-posters/train-frottement.jpg',
    fps: 25,
    defaultMass: 0.30,
    rulerRealLength: 0.50,
    autoCalibrate: {
      rulerP1: { x: 140, y: 570 },
      rulerP2: { x: 870, y: 570 },
      origin: { x: 140, y: 529 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-train-accelerated',
    title: 'FizziQ: Accelerated Motion (Train Launch)',
    source: 'FizziQ',
    category: '1D Kinematics & Acceleration',
    description: 'Model train accelerating continuously from rest. Quadratic regression fit y = At² + Bt + C computes uniform acceleration a = 2A.',
    videoUrl: '/videos/fizziq/train-accelere.mp4',
    posterUrl: '/images/cinematique-posters/train-accelere.jpg',
    fps: 25,
    defaultMass: 0.35,
    rulerRealLength: 0.50,
    autoCalibrate: {
      rulerP1: { x: 140, y: 570 },
      rulerP2: { x: 870, y: 570 },
      origin: { x: 140, y: 529 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-freefall-ball',
    title: 'FizziQ: Free Fall of a Ball',
    source: 'FizziQ',
    category: '1D Kinematics & Gravity',
    description: 'High-visibility ball dropped from rest. Verify free fall under gravity without air resistance and measure g = 9.8 m/s².',
    videoUrl: '/videos/fizziq/chute-libre-balle.mp4',
    posterUrl: '/images/cinematique-posters/chute-libre-balle.jpg',
    fps: 30,
    defaultMass: 0.058,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 147, y: 1634 },
      rulerP2: { x: 147, y: 930 },
      origin: { x: 651, y: 165 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-parabola-cinematique',
    title: 'FizziQ: Parabolic Motion (Cinematique)',
    source: 'FizziQ',
    category: '2D Kinematics & Projectiles',
    description: 'FizziQ Cinematique 2D projectile curve. Demonstrate constant vx and quadratic vertical displacement y(t).',
    videoUrl: '/videos/fizziq/parabole.mp4',
    posterUrl: '/images/cinematique-posters/parabole.jpg',
    fps: 30,
    defaultMass: 0.15,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 140, y: 963 },
      rulerP2: { x: 140, y: 478 },
      origin: { x: 140, y: 963 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-spacex-landing',
    title: 'FizziQ: SpaceX Falcon 9 Propulsive Landing',
    source: 'FizziQ',
    category: 'Rocketry & Advanced Dynamics',
    description: 'Orbital rocket booster performing a vertical suicide-burn propulsive landing. Measure decelerating velocity vector and touch touchdown.',
    videoUrl: '/videos/fizziq/atterrissage-spacex.mp4',
    fps: 30,
    defaultMass: 25000,
    rulerRealLength: 41.2,
    autoCalibrate: {
      rulerP1: { x: 300, y: 150 },
      rulerP2: { x: 300, y: 450 },
      origin: { x: 300, y: 460 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-pendulum-cinematique',
    title: 'FizziQ: Simple Harmonic Pendulum',
    source: 'FizziQ',
    category: 'Harmonic Motion & Oscillations',
    description: 'Standard physics pendulum bob oscillation. Confirm period T = 2π√(L/g) and harmonic kinetic-potential energy conservation.',
    videoUrl: '/videos/fizziq/pendule.mp4',
    posterUrl: '/images/cinematique-posters/pendule.jpg',
    fps: 30,
    defaultMass: 0.20,
    rulerRealLength: 0.40,
    autoCalibrate: {
      rulerP1: { x: 165, y: 591 },
      rulerP2: { x: 411, y: 591 },
      origin: { x: 635, y: 378 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-newton-cradle',
    title: "FizziQ: Newton's Cradle Oscillations",
    source: 'FizziQ',
    category: 'Collisions & Momentum Conservation',
    description: 'Classic Newton cradle spheres transferring momentum through elastic acoustic stress waves. Track release and rebound amplitudes.',
    videoUrl: '/videos/fizziq/pendule-newton.mp4',
    posterUrl: '/images/cinematique-posters/pendule-newton.jpg',
    fps: 30,
    defaultMass: 0.05,
    rulerRealLength: 0.2,
    autoCalibrate: {
      rulerP1: { x: 220, y: 340 },
      rulerP2: { x: 420, y: 340 },
      origin: { x: 320, y: 340 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-elastic-collision',
    title: 'FizziQ: 2D Elastic Collision',
    source: 'FizziQ',
    category: 'Collisions & Momentum Conservation',
    description: 'High-framerate 60 fps recording of colliding billiard spheres. Track both bodies to verify conservation of linear momentum (Px, Py).',
    videoUrl: '/videos/fizziq/collision.mp4',
    posterUrl: '/images/cinematique-posters/collision.jpg',
    fps: 60,
    defaultMass: 0.20,
    rulerRealLength: 0.50,
    autoCalibrate: {
      rulerP1: { x: 455, y: 984 },
      rulerP2: { x: 455, y: 567 },
      origin: { x: 345, y: 629 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-impact-choc',
    title: 'FizziQ: Inelastic Impact & Shock',
    source: 'FizziQ',
    category: 'Collisions & Momentum Conservation',
    description: 'Sudden impact collision between objects measuring impulse J = Δp and kinetic energy dissipation into deformation and heat.',
    videoUrl: '/videos/fizziq/choc.mp4',
    posterUrl: '/images/cinematique-posters/choc.jpg',
    fps: 30,
    defaultMass: 0.18,
    rulerRealLength: 0.4,
    autoCalibrate: {
      rulerP1: { x: 180, y: 360 },
      rulerP2: { x: 460, y: 360 },
      origin: { x: 320, y: 360 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-cycloid',
    title: 'FizziQ: Rolling Wheel Cycloid Curve',
    source: 'FizziQ',
    category: 'Rotational Physics & Special Curves',
    description: 'High-speed 60 fps recording of a marker on a rolling wheel tracing a parametric cycloid x = r(θ - sin θ), y = r(1 - cos θ).',
    videoUrl: '/videos/fizziq/cycloide.mp4',
    posterUrl: '/images/cinematique-posters/cycloide.jpg',
    fps: 60,
    defaultMass: 0.25,
    rulerRealLength: 0.3,
    autoCalibrate: {
      rulerP1: { x: 120, y: 380 },
      rulerP2: { x: 500, y: 380 },
      origin: { x: 120, y: 380 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-bubble-liquid',
    title: 'FizziQ: Bubble Rising in Viscous Liquid',
    source: 'FizziQ',
    category: 'Fluid Dynamics & Viscosity',
    description: 'Air bubble rising through viscous fluid under Archimedes buoyancy force balanced by Stokes drag, reaching constant terminal velocity.',
    videoUrl: '/videos/fizziq/bulle-liquide.mp4',
    posterUrl: '/images/cinematique-posters/bulle-liquide.jpg',
    fps: 30,
    defaultMass: 0.001,
    rulerRealLength: 0.4,
    autoCalibrate: {
      rulerP1: { x: 280, y: 120 },
      rulerP2: { x: 280, y: 440 },
      origin: { x: 280, y: 440 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-juggler',
    title: 'FizziQ: Juggler 3-Ball Cascade',
    source: 'FizziQ',
    category: '2D Kinematics & Projectiles',
    description: 'Multi-body projectile tracking of 3 juggling balls tracing interleaved parabolic arcs with synchronized apex turning points.',
    videoUrl: '/videos/fizziq/jongleur.mp4',
    posterUrl: '/images/cinematique-posters/jongleur.jpg',
    fps: 30,
    defaultMass: 0.12,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 200, y: 480 },
      rulerP2: { x: 440, y: 480 },
      origin: { x: 320, y: 480 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-traffic-flow',
    title: 'FizziQ: Highway Traffic Flow & Phantom Jam',
    source: 'FizziQ',
    category: 'Complex Systems & Traffic Flow',
    description: 'Multi-lane highway traffic tracking vehicle density waves and the backwards propagation speed of a phantom congestion jam.',
    videoUrl: '/videos/fizziq/route-embouteillages.mp4',
    posterUrl: '/images/cinematique-posters/route-embouteillages.jpg',
    fps: 30,
    defaultMass: 1500,
    rulerRealLength: 25.0,
    autoCalibrate: {
      rulerP1: { x: 100, y: 300 },
      rulerP2: { x: 500, y: 300 },
      origin: { x: 100, y: 300 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-football-penalty',
    title: 'FizziQ: Football Penalty Kick Flight',
    source: 'FizziQ',
    category: 'Sports Kinematics & Biomechanics',
    description: 'Soccer ball penalty kick launch and trajectory towards the goal. Track launch speed v0, angle, and flight duration.',
    videoUrl: '/videos/fizziq/football-penalty.mp4',
    posterUrl: '/images/cinematique-posters/football-penalty.jpg',
    fps: 30,
    defaultMass: 0.43,
    rulerRealLength: 2.44,
    autoCalibrate: {
      rulerP1: { x: 450, y: 220 },
      rulerP2: { x: 450, y: 440 },
      origin: { x: 150, y: 440 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-basketball-shot',
    title: 'FizziQ: Basketball Free Throw',
    source: 'FizziQ',
    category: 'Sports Kinematics & Biomechanics',
    description: 'High-arc basketball jump shot. Fit parabolic trajectory y(x) and determine launch angle and entry angle into the hoop.',
    videoUrl: '/videos/fizziq/basket.mp4',
    posterUrl: '/images/cinematique-posters/basket.jpg',
    fps: 17,
    defaultMass: 0.62,
    rulerRealLength: 3.05,
    autoCalibrate: {
      rulerP1: { x: 480, y: 160 },
      rulerP2: { x: 480, y: 460 },
      origin: { x: 140, y: 460 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-tennis-shot',
    title: 'FizziQ: Tennis Stroke & Ball Dynamics',
    source: 'FizziQ',
    category: 'Sports Kinematics & Biomechanics',
    description: 'Tennis ball launch off the racket face across the court net. Track ball exit velocity and trajectory flattening.',
    videoUrl: '/videos/fizziq/tennis.mp4',
    posterUrl: '/images/cinematique-posters/tennis.jpg',
    fps: 30,
    defaultMass: 0.058,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 150, y: 450 },
      rulerP2: { x: 350, y: 450 },
      origin: { x: 150, y: 450 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-golf-swing',
    title: 'FizziQ: Golf Clubhead Swing & Launch',
    source: 'FizziQ',
    category: 'Sports Kinematics & Biomechanics',
    description: 'High-framerate 60 fps recording of golf club impact. Measure clubhead angular velocity and ball initial launch speed.',
    videoUrl: '/videos/fizziq/golf.mp4',
    posterUrl: '/images/cinematique-posters/golf.jpg',
    fps: 60,
    defaultMass: 0.046,
    rulerRealLength: 1.1,
    autoCalibrate: {
      rulerP1: { x: 260, y: 300 },
      rulerP2: { x: 260, y: 460 },
      origin: { x: 260, y: 460 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-badminton-smash',
    title: 'FizziQ: Badminton Aerodynamic Drag Flight',
    source: 'FizziQ',
    category: 'Sports Kinematics & Aerodynamic Drag',
    description: 'High-drag flight of a badminton shuttlecock. Observe non-parabolic steep descent caused by quadratic air resistance F_drag ∝ v².',
    videoUrl: '/videos/fizziq/badminton.mp4',
    posterUrl: '/images/cinematique-posters/badminton.jpg',
    fps: 25,
    defaultMass: 0.005,
    rulerRealLength: 1.5,
    autoCalibrate: {
      rulerP1: { x: 200, y: 420 },
      rulerP2: { x: 450, y: 420 },
      origin: { x: 150, y: 420 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-curling-stone',
    title: 'FizziQ: Curling Stone Ice Slide',
    source: 'FizziQ',
    category: 'Sports Kinematics & Friction',
    description: '20 kg granite curling stone decelerating smoothly along pebbled ice sheet. Calculate kinetic friction coefficient μ_k ≈ 0.01.',
    videoUrl: '/videos/fizziq/curling.mp4',
    posterUrl: '/images/cinematique-posters/curling.jpg',
    fps: 25,
    defaultMass: 19.96,
    rulerRealLength: 3.66,
    autoCalibrate: {
      rulerP1: { x: 100, y: 320 },
      rulerP2: { x: 480, y: 320 },
      origin: { x: 100, y: 320 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-javelin-throw',
    title: 'FizziQ: Olympic Javelin Aerodynamic Flight',
    source: 'FizziQ',
    category: 'Sports Kinematics & Aerodynamics',
    description: 'Javelin flight showing aerofoil lift, angle of attack, center-of-gravity pitch stability, and range optimization.',
    videoUrl: '/videos/fizziq/javelot.mp4',
    posterUrl: '/images/cinematique-posters/javelot.jpg',
    fps: 30,
    defaultMass: 0.80,
    rulerRealLength: 2.6,
    autoCalibrate: {
      rulerP1: { x: 150, y: 400 },
      rulerP2: { x: 480, y: 400 },
      origin: { x: 150, y: 400 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-discus-throw',
    title: 'FizziQ: Discus Throw Rotational Spin',
    source: 'FizziQ',
    category: 'Sports Kinematics & Biomechanics',
    description: 'Rotational turn and release of a competition discus. Calculate tangential velocity v = ω r and release angle.',
    videoUrl: '/videos/fizziq/lancer-disque.mp4',
    posterUrl: '/images/cinematique-posters/lancer-disque.jpg',
    fps: 30,
    defaultMass: 2.0,
    rulerRealLength: 2.5,
    autoCalibrate: {
      rulerP1: { x: 200, y: 420 },
      rulerP2: { x: 450, y: 420 },
      origin: { x: 200, y: 420 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-hammer-throw',
    title: 'FizziQ: Hammer Throw Centripetal Force',
    source: 'FizziQ',
    category: 'Rotational Physics & Sports',
    description: 'Steel hammer rotating on a wire. Compute rotational frequency, tension, and massive centripetal force Fc = m v²/r.',
    videoUrl: '/videos/fizziq/lancer-marteau.mp4',
    posterUrl: '/images/cinematique-posters/lancer-marteau.jpg',
    fps: 30,
    defaultMass: 7.26,
    rulerRealLength: 1.2,
    autoCalibrate: {
      rulerP1: { x: 220, y: 350 },
      rulerP2: { x: 400, y: 350 },
      origin: { x: 300, y: 350 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-pole-vault',
    title: 'FizziQ: Pole Vault Energy Transformation',
    source: 'FizziQ',
    category: 'Energetics & Biomechanics',
    description: 'Kinetic energy of runner converts to elastic potential in fiberglass pole, then lifts athlete into gravitational potential energy Ep = mgh.',
    videoUrl: '/videos/fizziq/saut-perche.mp4',
    posterUrl: '/images/cinematique-posters/saut-perche.jpg',
    fps: 30,
    defaultMass: 75.0,
    rulerRealLength: 5.0,
    autoCalibrate: {
      rulerP1: { x: 380, y: 150 },
      rulerP2: { x: 380, y: 450 },
      origin: { x: 180, y: 450 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-platform-diving',
    title: 'FizziQ: Platform Diving Angular Momentum',
    source: 'FizziQ',
    category: 'Rotational Physics & Biomechanics',
    description: 'Diver somersaulting from 10m platform. Demonstrates conservation of angular momentum L = Iω: tucking decreases I, increasing spin rate ω.',
    videoUrl: '/videos/fizziq/plongeon.mp4',
    posterUrl: '/images/cinematique-posters/plongeon.jpg',
    fps: 24,
    defaultMass: 65.0,
    rulerRealLength: 10.0,
    autoCalibrate: {
      rulerP1: { x: 280, y: 100 },
      rulerP2: { x: 280, y: 450 },
      origin: { x: 280, y: 450 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-ski-downhill',
    title: 'FizziQ: Olympic Downhill Skiing Velocity',
    source: 'FizziQ',
    category: 'Sports Kinematics & Inclined Planes',
    description: 'Downhill alpine racer on snow incline. Analyze inclined acceleration vector a = g(sin θ - μ cos θ) and wind drag resistance.',
    videoUrl: '/videos/fizziq/ski-descente-jo.mp4',
    posterUrl: '/images/cinematique-posters/ski-descente-jo.jpg',
    fps: 25,
    defaultMass: 85.0,
    rulerRealLength: 15.0,
    autoCalibrate: {
      rulerP1: { x: 150, y: 400 },
      rulerP2: { x: 450, y: 400 },
      origin: { x: 150, y: 400 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-speed-skating',
    title: 'FizziQ: Speed Skating Corner Banking Lean',
    source: 'FizziQ',
    category: 'Sports Kinematics & Biomechanics',
    description: 'Olympic speed skater leaning into a high-speed curve. Correlate velocity v with lean angle tan θ = v²/(r*g).',
    videoUrl: '/videos/fizziq/patinage-vitesse-jo.mp4',
    posterUrl: '/images/cinematique-posters/patinage-vitesse-jo.jpg',
    fps: 25,
    defaultMass: 72.0,
    rulerRealLength: 12.0,
    autoCalibrate: {
      rulerP1: { x: 180, y: 380 },
      rulerP2: { x: 440, y: 380 },
      origin: { x: 180, y: 380 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-bicycle-motion',
    title: 'FizziQ: Bicycle Wheel & Frame Motion',
    source: 'FizziQ',
    category: 'Rotational Physics & Biomechanics',
    description: 'Forward travel of a bicycle. Correlate bicycle linear velocity v_frame with wheel rim rolling angular velocity v = ω r.',
    videoUrl: '/videos/fizziq/velo.mp4',
    posterUrl: '/images/cinematique-posters/velo.jpg',
    fps: 30,
    defaultMass: 80.0,
    rulerRealLength: 1.8,
    autoCalibrate: {
      rulerP1: { x: 160, y: 420 },
      rulerP2: { x: 480, y: 420 },
      origin: { x: 160, y: 420 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-cyclist-track',
    title: 'FizziQ: Velodrome Track Cycling Banking',
    source: 'FizziQ',
    category: 'Sports Kinematics & Dynamics',
    description: 'Track cycling on steep banked velodrome wooden turn. Calculate optimal banking speed where friction force is zero.',
    videoUrl: '/videos/fizziq/cycliste-piste.mp4',
    posterUrl: '/images/cinematique-posters/cycliste-piste.jpg',
    fps: 30,
    defaultMass: 78.0,
    rulerRealLength: 8.0,
    autoCalibrate: {
      rulerP1: { x: 180, y: 380 },
      rulerP2: { x: 480, y: 380 },
      origin: { x: 180, y: 380 },
      invertY: true,
    },
  },
  {
    id: 'fizziq-toyota-robot',
    title: 'FizziQ: Toyota CUE Basketball Robot',
    source: 'FizziQ',
    category: 'Robotics & Kinematics',
    description: 'Humanoid robotics arm calculating parabolic projectile kinematics to sink 100% accurate basketball shots from across the court.',
    videoUrl: '/videos/fizziq/robot-toyota-basket.mp4',
    posterUrl: '/images/cinematique-posters/robot-toyota-basket.jpg',
    fps: 24,
    defaultMass: 90.0,
    rulerRealLength: 3.05,
    autoCalibrate: {
      rulerP1: { x: 460, y: 180 },
      rulerP2: { x: 460, y: 440 },
      origin: { x: 200, y: 440 },
      invertY: true,
    },
  },

  // =========================================================================
  // REAL OPEN SOURCE PHYSICS TRACKER LIBRARY EXPERIMENTS (19 REAL EXPERIMENTS)
  // =========================================================================
  {
    id: 'tracker-ball-toss',
    title: 'Tracker: Classic Ball Toss (2D Projectile)',
    source: 'Tracker',
    category: '2D Kinematics & Projectiles',
    description: 'Classic Open Source Physics Tracker video of a high ball toss. Track vx constant and vy under constant gravitational acceleration.',
    videoUrl: '/videos/tracker_ball_toss.mp4',
    fps: 30,
    defaultMass: 0.14,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 180, y: 150 },
      rulerP2: { x: 180, y: 450 },
      origin: { x: 150, y: 460 },
      invertY: true,
    },
  },
  {
    id: 'tracker-collision-pucks',
    title: 'Tracker: 2D Puck Collision (Center of Mass)',
    source: 'Tracker',
    category: 'Collisions & Momentum Conservation',
    description: 'Two pucks colliding on an air table. Track Object 1 & Object 2 to verify conservation of linear momentum and constant Center of Mass velocity.',
    videoUrl: '/videos/tracker_collision_pucks.mp4',
    fps: 30,
    defaultMass: 0.25,
        rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 20, y: 10 },
      rulerP2: { x: 20, y: 230 },
      origin: { x: 160, y: 230 },
      invertY: true,
    },
  },
  {
    id: 'tracker-two-carts',
    title: 'Tracker: Two Carts 1D Collision',
    source: 'Tracker',
    category: 'Collisions & Momentum Conservation',
    description: 'Two dynamics carts on a low-friction track in an elastic collision. Check momentum conservation P = m1*v1 + m2*v2.',
    videoUrl: '/videos/tracker_two_carts.mp4',
    fps: 30,
    defaultMass: 0.50,
        rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 20, y: 220 },
      rulerP2: { x: 636, y: 220 },
      origin: { x: 90, y: 340 },
      invertY: true,
    },
  },
  {
    id: 'tracker-bicycle-wheel',
    title: 'Tracker: Bicycle Wheel Rotation',
    source: 'Tracker',
    category: 'Rotational Physics & Special Curves',
    description: 'Bicycle wheel spinning on an axle. Measure angular velocity omega (rad/s), centripetal acceleration ac = v^2/r, and rotational inertia.',
    videoUrl: '/videos/tracker_bicycle_wheel.mp4',
    fps: 30,
    defaultMass: 1.8,
        rulerRealLength: 0.65,
    autoCalibrate: {
      rulerP1: { x: 245, y: 67 },
      rulerP2: { x: 245, y: 263 },
      origin: { x: 245, y: 165 },
      invertY: true,
    },
  },
  {
    id: 'tracker-bouncing-ball',
    title: 'Tracker: Bouncing Ball (Coefficient of Restitution)',
    source: 'Tracker',
    category: '1D Kinematics & Gravity',
    description: 'High-contrast ball dropped and bouncing repeatedly. Measure coefficient of restitution e = sqrt(h2/h1) and energy loss per bounce.',
    videoUrl: '/videos/tracker_ball.mp4',
    fps: 30,
    defaultMass: 0.10,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 200, y: 100 },
      rulerP2: { x: 200, y: 450 },
      origin: { x: 200, y: 450 },
      invertY: true,
    },
  },
  {
    id: 'tracker-balldrop',
    title: 'Tracker: High-Precision Ball Drop (Grid)',
    source: 'Tracker',
    category: '1D Kinematics & Gravity',
    description: 'Vertical drop of a steel ball in front of a high-precision grid background. Measure g = 9.80 m/s² with minimal parallax error.',
    videoUrl: '/videos/tracker_balldrop.mp4',
    fps: 30,
    defaultMass: 0.20,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 250, y: 100 },
      rulerP2: { x: 250, y: 450 },
      origin: { x: 250, y: 450 },
      invertY: true,
    },
  },
  {
    id: 'tracker-balltossup',
    title: 'Tracker: 1D Ball Toss Upward (Apex Turning Point)',
    source: 'Tracker',
    category: '1D Kinematics & Gravity',
    description: 'Vertical ball toss rising to maximum height and falling back down. Study turning point velocity vy = 0 and continuous acceleration a = -g.',
    videoUrl: '/videos/tracker_balltossup.mp4',
    fps: 30,
    defaultMass: 0.15,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 280, y: 120 },
      rulerP2: { x: 280, y: 460 },
      origin: { x: 280, y: 460 },
      invertY: true,
    },
  },
  {
    id: 'tracker-pendulum-harm',
    title: 'Tracker: Simple Harmonic Pendulum',
    source: 'Tracker',
    category: 'Harmonic Motion & Oscillations',
    description: 'Single-bob harmonic pendulum. Confirm period formula T = 2π√(L/g) and examine angular acceleration alpha.',
    videoUrl: '/videos/tracker_pendulum.mp4',
    fps: 30,
    defaultMass: 0.25,
        rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 160, y: 36 },
      rulerP2: { x: 160, y: 206 },
      origin: { x: 160, y: 36 },
      invertY: true,
    },
  },
  {
    id: 'tracker-pendulum-drag',
    title: 'Tracker: Damped Drag Pendulum (Exponential Decay)',
    source: 'Tracker',
    category: 'Harmonic Motion & Oscillations',
    description: 'Pendulum swinging with aerodynamic paddle drag. Fit exponential envelope A(t) = A0 * e^(-γt) to determine damping coefficient.',
    videoUrl: '/videos/tracker_pendulum_drag.mp4',
    fps: 30,
    defaultMass: 0.15,
    rulerRealLength: 0.8,
    autoCalibrate: {
      rulerP1: { x: 320, y: 100 },
      rulerP2: { x: 320, y: 440 },
      origin: { x: 320, y: 440 },
      invertY: true,
    },
  },
  {
    id: 'tracker-spring-wars',
    title: 'Tracker: Coupled Spring Oscillators',
    source: 'Tracker',
    category: 'Harmonic Motion & Oscillations',
    description: 'Two coupled carts oscillating on springs between end-stops. Observe energy exchange, beats, and normal modes of oscillation.',
    videoUrl: '/videos/tracker_spring_wars.mp4',
    fps: 30,
    defaultMass: 0.50,
    rulerRealLength: 1.2,
    autoCalibrate: {
      rulerP1: { x: 100, y: 350 },
      rulerP2: { x: 500, y: 350 },
      origin: { x: 300, y: 350 },
      invertY: true,
    },
  },
  {
    id: 'tracker-bouncing-cart-spring',
    title: 'Tracker: Bouncing Cart with Spring Ends',
    source: 'Tracker',
    category: 'Collisions & Momentum Conservation',
    description: 'Dynamics cart rebounding elastically against a spring barrier. Analyze deceleration phase during spring compression and Hooke force F = -kx.',
    videoUrl: '/videos/tracker_bouncing_cart_spring.mp4',
    fps: 30,
    defaultMass: 0.50,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 80, y: 340 },
      rulerP2: { x: 520, y: 340 },
      origin: { x: 80, y: 340 },
      invertY: true,
    },
  },
  {
    id: 'tracker-shm-scale',
    title: 'Tracker: Vertical Spring Scale SHM',
    source: 'Tracker',
    category: 'Harmonic Motion & Oscillations',
    description: 'Mass suspended from a vertical spring scale oscillating in simple harmonic motion. Determine spring constant k = m*ω².',
    videoUrl: '/videos/tracker_shmscale.mp4',
    fps: 30,
    defaultMass: 0.20,
        rulerRealLength: 0.15,
    autoCalibrate: {
      rulerP1: { x: 133, y: 30 },
      rulerP2: { x: 133, y: 78 },
      origin: { x: 133, y: 110 },
      invertY: true,
    },
  },
  {
    id: 'tracker-block-on-cart',
    title: 'Tracker: Static vs Kinetic Friction on Cart',
    source: 'Tracker',
    category: 'Dynamics & Friction',
    description: 'A block resting on top of an accelerating cart. Observe the transition point where static friction fails and kinetic slip begins.',
    videoUrl: '/videos/tracker_blockoncart.mp4',
    fps: 30,
    defaultMass: 0.25,
        rulerRealLength: 0.50,
    autoCalibrate: {
      rulerP1: { x: 20, y: 150 },
      rulerP2: { x: 280, y: 150 },
      origin: { x: 260, y: 150 },
      invertY: true,
    },
  },
  {
    id: 'tracker-tipping-cylinders',
    title: 'Tracker: Rotational Stability & Tipping Angle',
    source: 'Tracker',
    category: 'Rotational Physics & Special Curves',
    description: 'Cylinders of various aspect ratios tilted on an incline. Measure critical toppling angle θ_crit = arctan(diameter / height).',
    videoUrl: '/videos/tracker_tippingcylinders.mp4',
    fps: 30,
    defaultMass: 0.30,
        rulerRealLength: 0.90,
    autoCalibrate: {
      rulerP1: { x: 280, y: 72 },
      rulerP2: { x: 10, y: 72 },
      origin: { x: 280, y: 160 },
      invertY: true,
    },
  },
  {
    id: 'tracker-flextrack-races',
    title: 'Tracker: Brachistochrone Curve Race',
    source: 'Tracker',
    category: '1D Kinematics & Gravity',
    description: 'Two balls racing on straight vs curved cycloidal inclines. Demonstrates the Brachistochrone curve of fastest descent.',
    videoUrl: '/videos/tracker_flextrackraces.mp4',
    fps: 30,
    defaultMass: 0.05,
        rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 45, y: 100 },
      rulerP2: { x: 290, y: 100 },
      origin: { x: 45, y: 100 },
      invertY: true,
    },
  },
  {
    id: 'tracker-cups-clips',
    title: 'Tracker: Independence of Horizontal & Vertical Motion',
    source: 'Tracker',
    category: '2D Kinematics & Projectiles',
    description: 'Classic physics demo dropping one object vertically while launching another horizontally simultaneously. Verify identical vertical fall times.',
    videoUrl: '/videos/tracker_cupsclips.mp4',
    fps: 30,
    defaultMass: 0.05,
        rulerRealLength: 2.0,
    autoCalibrate: {
      rulerP1: { x: 168, y: 36 },
      rulerP2: { x: 168, y: 204 },
      origin: { x: 168, y: 36 },
      invertY: true,
    },
  },
  {
    id: 'tracker-diabolo-cm',
    title: 'Tracker: Diabolo Toss (Center of Mass & Rotation)',
    source: 'Tracker',
    category: 'Rotational Physics & Special Curves',
    description: 'Spinning diabolo tossed in the air. Track rotation markers vs center of mass: center follows pure parabola while tips rotate.',
    videoUrl: '/videos/tracker_diabolo_cm.mp4',
    fps: 30,
    defaultMass: 0.22,
    rulerRealLength: 1.2,
    autoCalibrate: {
      rulerP1: { x: 200, y: 120 },
      rulerP2: { x: 200, y: 450 },
      origin: { x: 200, y: 450 },
      invertY: true,
    },
  },
  {
    id: 'tracker-skater-300fps',
    title: 'Tracker: Ice Skater High-Speed Spin (300 fps)',
    source: 'Tracker',
    category: 'Rotational Physics & Special Curves',
    description: 'Ultra-slow-motion 300 fps recording of a figure skater spin. Quantify moment of inertia reduction and angular acceleration during arm retraction.',
    videoUrl: '/videos/tracker_skater_300fps.mp4',
    fps: 300,
    defaultMass: 55.0,
        rulerRealLength: 1.65,
    autoCalibrate: {
      rulerP1: { x: 240, y: 105 },
      rulerP2: { x: 240, y: 285 },
      origin: { x: 240, y: 210 },
      invertY: true,
    },
  },
  {
    id: 'tracker-landing-long',
    title: 'Tracker: Athletic Long Jump Biomechanics',
    source: 'Tracker',
    category: 'Sports Kinematics & Biomechanics',
    description: 'Athlete takeoff, flight arc, and sandpit landing. Track center of mass trajectory, takeoff angle, and ground reaction impulse.',
    videoUrl: '/videos/tracker_landing_long.mp4',
    fps: 30,
    defaultMass: 72.0,
    rulerRealLength: 6.0,
    autoCalibrate: {
      rulerP1: { x: 100, y: 420 },
      rulerP2: { x: 500, y: 420 },
      origin: { x: 100, y: 420 },
      invertY: true,
    },
  },
  {
    id: 'tracker-which-lands-first',
    title: 'Tracker: Galileo Equivalence (Which Lands First?)',
    source: 'Tracker',
    category: '1D Kinematics & Gravity',
    description: 'Two spheres of different masses released from identical height. Test Galileo equivalence principle proving free-fall acceleration g is mass-independent.',
    videoUrl: '/videos/tracker_whichlandsfirst.mp4',
    fps: 30,
    defaultMass: 0.50,
    rulerRealLength: 1.5,
    autoCalibrate: {
      rulerP1: { x: 50, y: 30 },
      rulerP2: { x: 50, y: 220 },
      origin: { x: 105, y: 35 },
      invertY: true,
    },
  },
  {
    id: 'tracker-ball-toss-out',
    title: 'Tracker: Horizontal Launch Off Table (2D Projectile)',
    source: 'Tracker',
    category: '2D Kinematics & Projectiles',
    description: 'Steel ball rolls horizontally off an elevated lab bench. Demonstrate independence of constant horizontal velocity vx and vertical gravitational acceleration.',
    videoUrl: '/videos/tracker_balltossout.mp4',
    fps: 30,
    defaultMass: 0.15,
    rulerRealLength: 1.2,
    autoCalibrate: {
      rulerP1: { x: 120, y: 140 },
      rulerP2: { x: 120, y: 440 },
      origin: { x: 120, y: 140 },
      invertY: true,
    },
  },
  {
    id: 'tracker-pucks-collide-seq',
    title: 'Tracker: 2D Elastic Collision Strobe Sequence',
    source: 'Tracker',
    category: 'Dynamics & Momentum Conservation',
    description: 'High-contrast multi-frame strobe sequence of two colliding air table pucks. Track velocity vectors before and after impact to demonstrate 2D momentum conservation.',
    videoUrl: '/videos/tracker_puckscollidesequence.mp4',
    fps: 30,
    defaultMass: 0.15,
    rulerRealLength: 1.0,
    autoCalibrate: {
      rulerP1: { x: 20, y: 220 },
      rulerP2: { x: 300, y: 220 },
      origin: { x: 160, y: 120 },
      invertY: true,
    },
  },
  {
    id: 'tracker-uniform-ball-fast',
    title: 'Tracker: High-Speed Rolling Ball (Galilean Invariance)',
    source: 'Tracker',
    category: '1D Kinematics & Constant Velocity',
    description: 'Fast uniform motion across a precision metric grid. Measure high-speed linear velocity with zero horizontal acceleration.',
    videoUrl: '/videos/tracker_uniform_ball_fast.mp4',
    fps: 30,
    defaultMass: 0.20,
    rulerRealLength: 2.0,
    autoCalibrate: {
      rulerP1: { x: 50, y: 400 },
      rulerP2: { x: 590, y: 400 },
      origin: { x: 75, y: 240 },
      invertY: true,
    },
  },
  {
    id: 'tracker-uniform-ball-slow',
    title: 'Tracker: Low-Speed Steady Rolling Ball',
    source: 'Tracker',
    category: '1D Kinematics & Constant Velocity',
    description: 'Low-speed rolling sphere with negligible surface friction. Ideal for high-precision linear regression x vs t.',
    videoUrl: '/videos/tracker_uniform_ball_slow.mp4',
    fps: 30,
    defaultMass: 0.20,
    rulerRealLength: 2.0,
    autoCalibrate: {
      rulerP1: { x: 50, y: 400 },
      rulerP2: { x: 590, y: 400 },
      origin: { x: 85, y: 240 },
      invertY: true,
    },
  },
];

// Student Edition: Zero pre-analyzed videos. All 57 experiments start with clean slate for student tracking.
export const REAL_EXPERIMENT_VIDEOS: PhysicsExperimentSample[] = BASE_EXPERIMENT_VIDEOS;

